<script type="text/javascript">
    $jq(document).ready(function(){
         var enable_module = $jq('#enable_module').val();
         if(enable_module==0) return false;
         $jq('.top-cart-title').click(function() {
            $jq('.top-cart-content').toggle();
        });
    });


</script>
<?php 

$smbl = '';

if(Mage::app()->getStore()->getStoreId() == 2){ 
                
$smbl = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
//echo $smbl;
//exit();
 }

$_cartQty = $this->getSummaryCount() ;
$_cartQty = Mage::getModel('checkout/cart')->getQuote()->getItemsQty();
//echo $_cartQty;
//echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal());

if($_cartQty == 0)
{ ?>

<div class="mycart-top">
    <div class="cart_items">
        <?php //echo $_cartQty; ?>
    </div>
    <div class="cart_items">
        <?php 
        //echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); 
        ?>
    </div>
</div>
<?php  } else { ?>

<div class="mycart-top">
    <div class="cart_items">
        <?php echo intval($_cartQty); ?>
    </div>
    <div class="cart_total">
        <?php 
        echo "<span class='a_symb'>$smbl</span>";
        echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); 
        ?>
    </div>
</div>
 
<?php } ?>

<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
          <!--<span class="top-cart-icon"></span>-->
                <span class="top-cart-title">
                    <!--<span>Shopping Cart</span><br/>-->
                    <span>Shopping Cart</span>
                    <p><span><?php echo $_cartQty; ?> <?php if($_cartQty>1) { echo $this->__('items'); } else { echo $this->__('item'); } ?></span> - <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></p>
                    <div class="cart_arrow"></div>
                </span>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions_aciotn">
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>

                        <div class="actions">
                            <button type="button" title="<?php echo $this->__('Cart') ?>" class="button" onclick="setLocation('<?php echo Mage::helper("checkout/cart")->getCartUrl() ?>')"><span><span><?php echo $this->__('Cart') ?></span></span></button>
                        </div>
                        </div>
                    <?php endif ?>




                </div>
            </div>

    </div>
</div>
